#!/usr/bin/env sh

./vmaf
echo ""

echo "run adm:"
./vmaf adm yuv420p ../resource/yuv/src01_hrc00_576x324.yuv ../resource/yuv/src01_hrc01_576x324.yuv 576 324

echo "run ansnr:"
./vmaf ansnr yuv420p ../resource/yuv/src01_hrc00_576x324.yuv ../resource/yuv/src01_hrc01_576x324.yuv 576 324

echo "run motion:"
./vmaf motion yuv420p ../resource/yuv/src01_hrc00_576x324.yuv ../resource/yuv/src01_hrc01_576x324.yuv 576 324

echo "run vif:"
./vmaf vif yuv420p ../resource/yuv/src01_hrc00_576x324.yuv ../resource/yuv/src01_hrc01_576x324.yuv 576 324

echo "done."
