#!/bin/sh

if [ $# -lt 4 ]; then
    echo "Usage: $0 ref_path dis_path width height [model_path] [out_fmt]"
    exit
fi

REF_VIDEO=$1
DIS_VIDEO=$2
QUALITY_WIDTH=$3
QUALITY_HEIGHT=$4
MODEL_PATH=$5
OUT_FMT=$6
FFMPEG_PATH="ffmpeg"
VMAF_PATH="./run_vmaf"
YUV_FMT="yuv420p"
FILTER="format=$YUV_FMT,scale=$QUALITY_WIDTH:$QUALITY_HEIGHT"
OUTPUT_FILE="./workspace/workdir/ffmpeg2vmaf.out"
FIFO_REF=$OUTPUT_FILE.Ref.yuv
FIFO_DIS=$OUTPUT_FILE.Dis.yuv

VMAF_CMD="$VMAF_PATH $YUV_FMT $QUALITY_WIDTH $QUALITY_HEIGHT $FIFO_REF $FIFO_DIS"

if [ "$MODEL_PATH" != "" ]; then
	VMAF_CMD="$VMAF_CMD --model $MODEL_PATH"
fi

if [ "$OUT_FMT" != "" ]; then
	VMAF_CMD="$VMAF_CMD --out-fmt $OUT_FMT"
fi

echo $VMAF_CMD

rm -f $FIFO_REF
rm -f $FIFO_DIS

mkfifo $FIFO_REF
mkfifo $FIFO_DIS

nohup $FFMPEG_PATH -y -i $REF_VIDEO -an -vsync 0 -vf $FILTER -f rawvideo - 2>$FIFO_REF.stderr > $FIFO_REF &
nohup $FFMPEG_PATH -y -i $DIS_VIDEO -an -vsync 0 -vf $FILTER -f rawvideo - 2>$FIFO_DIS.stderr > $FIFO_DIS &
$VMAF_CMD

rm -f $FIFO_REF
rm -f $FIFO_DIS
rm -f $FIFO_REF.stderr
rm -f $FIFO_DIS.stderr
