#!/usr/bin/env sh

# Note: Running unit tests via this will only work in docker, with all dependencies `pip install`-ed globally
# A better way to run the unit tests is via a venv (which can be easily done with pygradle)

#echo "Run tests in python/test..."
cd python
PYTHONPATH=src python -m unittest discover -t . -s test -p '*_test.py'
cd ..
