#!/usr/bin/env sh

echo "Run doctests in python/tools..."
PYTHONPATH=python/src python -m doctest python/src/vmaf/tools/misc.py
PYTHONPATH=python/src python -m doctest python/src/vmaf/tools/stats.py

#echo "Run tests in feature/test..."
PYTHONPATH=python/src python -m unittest discover -s feature/test -p '*_test.py'

#echo "Run tests in python/test..."
PYTHONPATH=python/src python -m unittest discover -s python/test -p '*_test.py'
