/**
 *
 *  Copyright 2016-2026 Netflix, Inc.
 *
 *     Licensed under the BSD+Patent License (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         https://opensource.org/licenses/BSDplusPatent
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

#ifndef __VMAF_SRC_FEATURE_CUDA_CAMBI_CUDA_H__
#define __VMAF_SRC_FEATURE_CUDA_CAMBI_CUDA_H__

/*
 * Generated by bin2c from the compiled fatbin. The symbol name is
 * "<meson key>_ptx", where <meson key> is the key used in cuda_cu_sources
 * in src/meson.build.
 */
extern const unsigned char cambi_derivative_ptx[];
extern const unsigned char cambi_decimate_ptx[];
extern const unsigned char cambi_filter_mode_ptx[];
extern const unsigned char cambi_spatial_mask_ptx[];
extern const unsigned char cambi_c_values_ptx[];
extern const unsigned char cambi_preprocess_ptx[];

#endif /* __VMAF_SRC_FEATURE_CUDA_CAMBI_CUDA_H__ */
