__copyright__ = "Copyright 2016, Netflix, Inc."
__license__ = "Apache, Version 2.0"

from mixin import TypeVersionEnabled

class Executor(TypeVersionEnabled):
    """
    Executor takes in a list of assets, and run calculation on them, and return
    a list of corresponding results. An Executor must specify a unique type
    and version combination (by the TYPE and VERSION attribute), so that the
    Result generated by it can be identified.
    """

    def __init__(self):
        TypeVersionEnabled.__init__(self)

    @property
    def executor_id(self):
        return TypeVersionEnabled.get_type_version_string(self)
