__copyright__ = "Copyright 2016, Netflix, Inc."
__license__ = "Apache, Version 2.0"

from executor import Executor
from result import Result

class FeatureExtractor(Executor):
    """
    FeatureExtractor takes in a list of assets, and run feature extraction on
    them, and return a list of corresponding results. A FeatureExtractor must
    specify a unique type and version combination (by the TYPE and VERSION
    attribute), so that the Result generated by it can be identified.
    """

    def _read_result(self, asset):
        result = {}
        result.update(self._get_feature_scores(asset))
        return Result(asset, self.executor_id, result)

