name: Docker
on:
  push:
    branches: [sycl]
  pull_request:
    branches: [sycl]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker Image
        run: docker build -t vmaf .
