name: Windows
on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build:
          - type: mingw
            msystem: MINGW64
            prefix: mingw-w64-x86_64
          - type: msvc
            bundled_winpthreads: true
          - type: msvc
            bundled_winpthreads: false

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache ccache files
        if: matrix.build.type == 'mingw'
        uses: actions/cache@v6
        with:
          path: |
            .ccache
          key: ${{ runner.os }}-${{ matrix.build.msystem }}-0-${{ hashFiles('**/*.c') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build.msystem }}-0-
            ${{ runner.os }}-${{ matrix.build.msystem }}-

      - name: Setup MSYS2
        if: matrix.build.type == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.build.msystem }}
          install: ${{ matrix.build.prefix }}-ccache ${{ matrix.build.prefix }}-nasm ${{ matrix.build.prefix }}-pkg-config ${{ matrix.build.prefix }}-gcc ${{ matrix.build.prefix }}-meson ${{ matrix.build.prefix }}-ninja vim make diffutils
          update: true
          path-type: inherit

      - name: Build (MINGW)
        if: matrix.build.type == 'mingw'
        shell: msys2 {0}
        run: |
          echo "name=CCACHE_DIR::$PWD/.ccache" >> $GITHUB_ENV
          meson setup libvmaf libvmaf/build --buildtype release --default-library static --prefix "$MINGW_PREFIX"
          meson install -C libvmaf/build
          meson test -C libvmaf/build --num-processes $(nproc)

          # Export MINGW_PREFIX to the global environment
          echo "MINGW_PREFIX=$(cygpath -m "$MINGW_PREFIX")" >> $GITHUB_ENV

      - name: Upload MINGW build
        if: matrix.build.type == 'mingw'
        uses: actions/upload-artifact@v7
        with:
          name: mingw-vmaf
          path: ${{ env.MINGW_PREFIX }}/bin/vmaf.exe

      - name: Setup MSVC environment
        if: matrix.build.type == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Meson and Ninja
        if: matrix.build.type == 'msvc'
        run: |
          pip install meson ninja

      - name: Install build tools
        if: matrix.build.type == 'msvc'
        run: |
          choco install xxd -y

      - name: Build (MSVC - bundled pthreads)
        if: matrix.build.type == 'msvc' && matrix.build.bundled_winpthreads == true
        shell: cmd
        run: |
          meson setup libvmaf libvmaf/build-msvc-bundled --buildtype release --default-library static --prefix C:/vmaf-install-msvc-bundled -Dbundled_winpthreads=true
          meson install -C libvmaf/build-msvc-bundled
          meson test -C libvmaf/build-msvc-bundled

      - name: Upload MSVC build (bundled)
        if: matrix.build.type == 'msvc' && matrix.build.bundled_winpthreads == true
        uses: actions/upload-artifact@v7
        with:
          name: msvc-vmaf-bundled
          path: C:/vmaf-install-msvc-bundled/bin/vmaf.exe

      - name: Install external pthreads (vcpkg)
        if: matrix.build.type == 'msvc' && matrix.build.bundled_winpthreads == false
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg.exe install pthreads:x64-windows

      - name: Build (MSVC - external pthreads)
        if: matrix.build.type == 'msvc' && matrix.build.bundled_winpthreads == false
        shell: cmd
        run: |
          set PATH=C:\vcpkg\installed\x64-windows\bin;%PATH%
          set INCLUDE=C:\vcpkg\installed\x64-windows\include;%INCLUDE%
          set LIB=C:\vcpkg\installed\x64-windows\lib;%LIB%

          meson setup libvmaf libvmaf/build-msvc-external --buildtype release --default-library static --prefix C:/vmaf-install-msvc-external -Dbundled_winpthreads=false
          meson install -C libvmaf/build-msvc-external
          meson test -C libvmaf/build-msvc-external

      - name: Upload MSVC build (external)
        if: matrix.build.type == 'msvc' && matrix.build.bundled_winpthreads == false
        uses: actions/upload-artifact@v7
        with:
          name: msvc-vmaf-external
          path: C:/vmaf-install-msvc-external/bin/vmaf.exe