name: Windows
on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build:
          - type: mingw
            msystem: MINGW64
            prefix: mingw-w64-x86_64
          - type: msvc

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup MSYS2
        if: matrix.build.type == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.build.msystem }}
          install: ${{ matrix.build.prefix }}-ccache ${{ matrix.build.prefix }}-nasm ${{ matrix.build.prefix }}-pkg-config ${{ matrix.build.prefix }}-gcc ${{ matrix.build.prefix }}-meson ${{ matrix.build.prefix }}-ninja vim make diffutils
          update: true
          path-type: inherit

      - name: Build (MINGW)
        if: matrix.build.type == 'mingw'
        shell: msys2 {0}
        run: |
          echo "name=CCACHE_DIR::$PWD/.ccache" >> $GITHUB_ENV
          meson setup libvmaf libvmaf/build --buildtype release --default-library static --prefix "$MINGW_PREFIX"
          meson install -C libvmaf/build
          meson test -C libvmaf/build --num-processes $(nproc)

          # Export MINGW_PREFIX to the global environment
          echo "MINGW_PREFIX=$(cygpath -m "$MINGW_PREFIX")" >> $GITHUB_ENV

      - name: Upload MINGW build
        if: matrix.build.type == 'mingw'
        uses: actions/upload-artifact@v5
        with:
          name: mingw-vmaf
          path: ${{ env.MINGW_PREFIX }}/bin/vmaf.exe

      - name: Setup MSVC environment
        if: matrix.build.type == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Meson and Ninja
        if: matrix.build.type == 'msvc'
        run: |
          pip install meson ninja

      - name: Install build tools
        if: matrix.build.type == 'msvc'
        run: |
          choco install xxd -y

      - name: Build (MSVC)
        if: matrix.build.type == 'msvc'
        shell: cmd
        run: |
          meson setup libvmaf libvmaf/build-msvc --buildtype release --default-library static --prefix C:/vmaf-install-msvc
          meson install -C libvmaf/build-msvc
          meson test -C libvmaf/build-msvc

      - name: Upload MSVC build
        if: matrix.build.type == 'msvc'
        uses: actions/upload-artifact@v5
        with:
          name: msvc-vmaf
          path: C:/vmaf-install-msvc/bin/vmaf.exe